name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Esto significa que el flujo de trabajo se ejecutará cuando hagas un push a la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest  # Esto especifica que el flujo de trabajo se ejecutará en una máquina con Ubuntu

    steps:
      - name: Check out the code
        uses: actions/checkout@v2  # Este paso descarga tu código fuente para el flujo de trabajo

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}  # Aquí se usa el secreto con las credenciales JSON

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash  # Instala Firebase CLI en el entorno de GitHub Actions

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_AUTH_TOKEN }}  # Despliega a Firebase Hosting
