name: Deploy to Firebase

on:
  push:
    branches:
      - master  # Esto indica que se ejecutará cuando haya un push a la rama 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest  # El sistema operativo donde se ejecutará el flujo de trabajo

    steps:
      - name: Check out the code
        uses: actions/checkout@v2  # Paso para verificar el código de tu repositorio

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}  # Aquí se agrega el secreto para autenticarse con Google Cloud

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash  # Esto instala la Firebase CLI en el entorno

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_AUTH_TOKEN }}  # Aquí usamos el token para autenticar el despliegue
